#!/usr/bin/env bash
# transfer a file from our client to a server:
len() {
    ((l = 0))
    for item in $@; do
        ((l++))
    done
    return $l
}
len $@
((l = $?))
if ((l < 3)); then
    echo -e "\e[31;45;7;3mUsage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\e[0m"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
