#!/usr/bin/env bash
# connecting to a server using private key
user="ubuntu"
privateKeyPath="~/.ssh/school"
ip="52.86.89.214"

ssh -i "$privateKeyPath" $user@$ip

# ssh -i ~/.ssh/school ubuntu@52.86.89.214 that's it
